In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import warnings
import seaborn as sns




In [2]:
#reading the data into a dataframe

Heart_df=pd.read_csv('python_files/new_heart_attack_data.csv')
Heart_df.head()


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   36    0   3       112   340    0        0      184      0      1.0      2   
1   39    0   2       120   200    0        0      160      1      1.0      2   
2   42    0   3       120   228    0        0      152      1      1.5      2   
3   44    0   2       120   184    0        0      142      0      1.0      2   
4   46    0   4       110   238    0        1      140      1      1.0      2   

   Discease_status  
0                0  
1                0  
2                0  
3                0  
4                0

In [3]:
#Checking for null values

print(Heart_df.isnull().sum())

age                0
sex                0
cp                 0
trestbps           0
chol               0
fbs                0
restecg            0
thalach            0
exang              0
oldpeak            0
slope              0
Discease_status    0
dtype: int64


In [4]:
#dropping na values

Heart_df=Heart_df.dropna()



In [5]:
# information about the data types of variables
#Heart_df['sex'].astype('float64')
Heart_df.info()


<class 'pandas.core.frame.DataFrame'>
Int64Index: 95 entries, 0 to 94
Data columns (total 12 columns):
age                95 non-null int64
sex                95 non-null int64
cp                 95 non-null int64
trestbps           95 non-null int64
chol               95 non-null int64
fbs                95 non-null int64
restecg            95 non-null int64
thalach            95 non-null int64
exang              95 non-null int64
oldpeak            95 non-null float64
slope              95 non-null int64
Discease_status    95 non-null int64
dtypes: float64(1), int64(11)
memory usage: 9.6 KB


In [6]:
# describe the whole data

Heart_df.describe()


age        sex         cp    trestbps        chol        fbs  \
count  95.000000  95.000000  95.000000   95.000000   95.000000  95.000000   
mean   50.631579   0.252632   3.463158  137.515789  261.978947   0.094737   
std     6.860390   0.436827   0.884987   18.682603   68.979951   0.294405   
min    31.000000   0.000000   1.000000   92.000000  117.000000   0.000000   
25%    47.000000   0.000000   3.000000  124.500000  217.500000   0.000000   
50%    52.000000   0.000000   4.000000  138.000000  260.000000   0.000000   
75%    55.000000   0.500000   4.000000  150.000000  293.000000   0.000000   
max    65.000000   1.000000   4.000000  200.000000  603.000000   1.000000   

         restecg     thalach      exang    oldpeak      slope  Discease_status  
count  95.000000   95.000000  95.000000  95.000000  95.000000        95.000000  
mean    0.231579  127.631579   0.736842   1.640000   1.905263         0.715789  
std     0.424079   20.989893   0.442683   0.796455   0.328559         0.453430  
min     0.000000   82.000000   0.000000   0.000000   1.000000         0.000000  
25%     0.000000  113.500000   0.000000   1.000000   2.000000         0.000000  
50%     0.000000  128.000000   1.000000   1.500000   2.000000         1.000000  
75%     0.000000  142.000000   1.000000   2.000000   2.000000         1.000000  
max     1.000000  184.000000   1.000000   5.000000   3.000000         1.000000

In [7]:
import pandas_profiling
pandas_profiling.ProfileReport(Heart_df)

C:\Users\ak620\Anaconda3\lib\site-packages\pandas_profiling\describe.py:392: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  variable_stats = pd.concat(ldesc, join_axes=pd.Index([names]), axis=1)


In [8]:
data=Heart_df['Discease_status'].value_counts()
print(data)



1    68
0    27
Name: Discease_status, dtype: int64


In [9]:
#Blue Graph indicate no heart desease and Orange Graph show Heart desease¶

import seaborn as sns
def plotTarget():
    sns.countplot(x='Discease_status', data=Heart_df, ax=ax)
    for i, p in enumerate(ax.patches):
        count=Heart_df['Discease_status'].value_counts().values[i]
        x=p.get_x()+ p.get_width() /2.
        y=p.get_height() + 3
        label='{:1.2f}'.format(count / float(Heart_df.shape[0]))
        ax.text(x, y,label, ha='center')
        
fig_target,ax=plt.subplots(nrows=1, ncols=1, figsize=(5, 2))
plotTarget()



In [10]:
#checking correlations

Heart_df.corr()


age       sex        cp  trestbps      chol       fbs  \
age              1.000000  0.077537 -0.078481  0.303375  0.150061  0.254488   
sex              0.077537  1.000000 -0.223335 -0.044814 -0.007589 -0.105361   
cp              -0.078481 -0.223335  1.000000  0.073547  0.138180 -0.006877   
trestbps         0.303375 -0.044814  0.073547  1.000000  0.180494  0.114807   
chol             0.150061 -0.007589  0.138180  0.180494  1.000000  0.286120   
fbs              0.254488 -0.105361 -0.006877  0.114807  0.286120  1.000000   
restecg          0.197841 -0.089465  0.136358  0.119036  0.105995 -0.007175   
thalach         -0.343819  0.100759 -0.341207 -0.191390 -0.126735  0.083178   
exang            0.027286 -0.202682  0.477347  0.190237  0.181672  0.111700   
oldpeak         -0.134926 -0.307610  0.160589  0.124429 -0.083306  0.056258   
slope           -0.128921 -0.202081  0.335442  0.020177  0.137913  0.203753   
Discease_status -0.098997 -0.385579  0.411058  0.199581  0.128034  0.203845   

                  restecg   thalach     exang   oldpeak     slope  \
age              0.197841 -0.343819  0.027286 -0.134926 -0.128921   
sex             -0.089465  0.100759 -0.202682 -0.307610 -0.202081   
cp               0.136358 -0.341207  0.477347  0.160589  0.335442   
trestbps         0.119036 -0.191390  0.190237  0.124429  0.020177   
chol             0.105995 -0.126735  0.181672 -0.083306  0.137913   
fbs             -0.007175  0.083178  0.111700  0.056258  0.203753   
restecg          1.000000 -0.095485  0.158072  0.085671  0.082780   
thalach         -0.095485  1.000000 -0.307075  0.012600 -0.170171   
exang            0.158072 -0.307075  1.000000  0.135778  0.411904   
oldpeak          0.085671  0.012600  0.135778  1.000000  0.173184   
slope            0.082780 -0.170171  0.411904  0.173184  1.000000   
Discease_status  0.013977 -0.249203  0.312416  0.323447  0.531428   

                 Discease_status  
age                    -0.098997  
sex                    -0.385579  
cp                      0.411058  
trestbps                0.199581  
chol                    0.128034  
fbs                     0.203845  
restecg                 0.013977  
thalach                -0.249203  
exang                   0.312416  
oldpeak                 0.323447  
slope                   0.531428  
Discease_status         1.000000

In [11]:

#Disease Probability Bar Plot

def plotAge():
    facet_grid = sns.FacetGrid(Heart_df, hue='Discease_status')
    facet_grid.map(sns.kdeplot, "age", shade=True, ax=axes[0])
    legend_labels = ['Disease false', 'Disease true']
    for t, l in zip(axes[0].get_legend().texts, legend_labels):
        t.set_text(l)
        axes[0].set(xlabel='age', ylabel='Density')

    avg = Heart_df[["age", "Discease_status"]].groupby(['age'], as_index=False).mean()
    sns.barplot(x='age', y='Discease_status', data=avg, ax=axes[1])
    axes[1].set(xlabel='age', ylabel='disease probability')

    plt.clf()

fig_age, axes = plt.subplots(nrows=2, ncols=1, figsize=(15, 8))
plotAge()

In [12]:

#Selecting label means selected Column to predict in df_X and input column in df_y
df_X= Heart_df.loc[:, Heart_df.columns != 'Discease_status']
df_y= Heart_df.loc[:, Heart_df.columns == 'Discease_status']



In [13]:
df_X
df_y

Discease_status
0                 0
1                 0
2                 0
3                 0
4                 0
..              ...
90                1
91                1
92                1
93                1
94                1

[95 rows x 1 columns]

In [14]:
#Recursive Feature Elimination
import statsmodels.api as sm
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
selected_features=[]
lr=LogisticRegression()
rfe=RFE(lr,20)

warnings.simplefilter('ignore')
rfe.fit(df_X.values,df_y.values)
print(rfe.support_)
print(rfe.ranking_)

for i, feature in enumerate(df_X.columns.values):
    if rfe.support_[i]:
        selected_features.append(feature)

df_selected_X = df_X[selected_features]
df_selected_y=df_y

lm=sm.Logit(df_selected_y,df_selected_X)
result = lm.fit()

print(result.summary2())
warnings.simplefilter('ignore')

[ True  True  True  True  True  True  True  True  True  True  True]
[1 1 1 1 1 1 1 1 1 1 1]
         Current function value: 0.307623
         Iterations: 35
                         Results: Logit
Model:              Logit            Pseudo R-squared: 0.485     
Dependent Variable: Discease_status  AIC:              80.4484   
Date:               2020-08-10 19:18 BIC:              108.5410  
No. Observations:   95               Log-Likelihood:   -29.224   
Df Model:           10               LL-Null:          -56.704   
Df Residuals:       84               LLR p-value:      3.2129e-08
Converged:          0.0000           Scale:            1.0000    
No. Iterations:     35.0000                                      
-----------------------------------------------------------------
          Coef.   Std.Err.     z    P>|z|     [0.025     0.975]  
-----------------------------------------------------------------
age      -0.1131     0.0507 -2.2313 0.0257     -0.2124    -0.0137
sex      -

In [15]:
#splitting data into test and train

from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test=train_test_split(df_selected_X,df_selected_y, test_size = 0.25, random_state =0)
columns = X_train.columns

In [16]:
#calculate accuracy of models
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
def cal_accuracy(y_test, y_predict): 
    
    print("\nConfusion Matrix: \n", 
    confusion_matrix(y_test, y_predict)) 
      
    print (f"\nAccuracy : {accuracy_score(y_test,y_predict)*100:0.3f}")

In [17]:
#logistic Regression

lr=LogisticRegression()
lr.fit(X_train,y_train)
y_predict=lr.predict(X_test)
print(f"Accuracy of Test Dataset: {lr.score(X_test,y_test):0.3f}")
print(f"Accuracy of Train Dataset: {lr.score(X_train,y_train):0.3f}")
warnings.simplefilter('ignore')

Accuracy of Test Dataset: 0.667
Accuracy of Train Dataset: 0.915


In [18]:
#prediction


print("Predicted values:") 
print(y_predict)
cal_accuracy(y_test, y_predict)

Predicted values:
[1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 0 0]

Confusion Matrix: 
 [[ 4  5]
 [ 3 12]]

Accuracy : 66.667


In [19]:
#support vector machine
from sklearn import svm
svm_linear = svm.SVC(kernel='linear')
svm_linear.fit(X_train,y_train)
warnings.simplefilter('ignore')
print(f"Accuracy of Test Dataset: {svm_linear.score(X_test,y_test):0.3f}")
print(f"Accuracy of Train Dataset: {svm_linear.score(X_train,y_train):0.3f}")

Accuracy of Test Dataset: 0.667
Accuracy of Train Dataset: 0.930


In [20]:
#prediction of svm
print("Predicted values:") 
print(y_predict)
cal_accuracy(y_test, y_predict)

Predicted values:
[1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 0 0]

Confusion Matrix: 
 [[ 4  5]
 [ 3 12]]

Accuracy : 66.667


In [21]:
#decision tree


from sklearn.tree import DecisionTreeClassifier
gini = DecisionTreeClassifier(criterion = "gini", random_state =100,max_depth=3, min_samples_leaf=5)
gini.fit(X_train, y_train)
warnings.simplefilter('ignore')
print(f"Accuracy of Test Dataset: {gini.score(X_test,y_test):0.3f}")
print(f"Accuracy of Train Dataset: {gini.score(X_train,y_train):0.3f}")

Accuracy of Test Dataset: 0.708
Accuracy of Train Dataset: 0.887


In [22]:
#prediction of decision tree

y_predict=gini.predict(X_test) 
print("Predicted values:\n")
print(y_predict) 
cal_accuracy(y_test, y_predict)

Predicted values:

[1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0]

Confusion Matrix: 
 [[ 3  6]
 [ 1 14]]

Accuracy : 70.833


In [23]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier

forest=RandomForestClassifier(n_estimators=100)
forest.fit(X_train,y_train)

warnings.simplefilter('ignore')
print(f"Accuracy of Test Dataset: {forest.score(X_test,y_test):0.3f}")
print(f"Accuracy of Train Dataset: {forest.score(X_train,y_train):0.3f}")

Accuracy of Test Dataset: 0.750
Accuracy of Train Dataset: 1.000


In [24]:
#random forest prediction

y_predict=forest.predict(X_test)
print("Predicted values:\n")
print(y_predict)
cal_accuracy(y_test, y_predict)

Predicted values:

[1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0]

Confusion Matrix: 
 [[ 3  6]
 [ 0 15]]

Accuracy : 75.000


In [25]:
#cross validation

from sklearn import model_selection
kfold=model_selection.KFold(n_splits=10, random_state=7)
models=[('Logistic Regression', lr), ('Support Vector Machine', svm_linear),('Decision Tree',gini),
        ('Random Forest',forest)]
warnings.simplefilter('ignore')

for model in models:
    results=model_selection.cross_val_score(model[1],X_train,y_train,cv=kfold,scoring='accuracy')
    print(f"Cross validated Accuracy of  {model[0]}:: {results.mean():.3f}")

Cross validated Accuracy of  Logistic Regression:: 0.830
Cross validated Accuracy of  Support Vector Machine:: 0.845
Cross validated Accuracy of  Decision Tree:: 0.816
Cross validated Accuracy of  Random Forest:: 0.787


In [26]:
models=pd.DataFrame({'Model':['Logistics Regression','SVM','Decision Tree','Random Forest'],
                     'Traning Accuracy':[(lr.score(X_train,y_train)),svm_linear.score(X_train,y_train),gini.score(X_train,y_train),forest.score(X_train,y_train)],
                     'Test Accuracy':[(lr.score(X_test,y_test)),svm_linear.score(X_test,y_test),gini.score(X_test,y_test),forest.score(X_test,y_test)]})
models.sort_values(by='Test Accuracy', ascending=False)

Model  Traning Accuracy  Test Accuracy
3         Random Forest          1.000000       0.750000
2         Decision Tree          0.887324       0.708333
0  Logistics Regression          0.915493       0.666667
1                   SVM          0.929577       0.666667